### ISSUE TITLE
Android Foregroung service code sample not working

### ISSUE THREAD

**Issue by mthnzbk** [putridparrot/blog-projects#308]
[Sample](https://github.com/putridparrot/blog-projects/tree/master/MauiAndroidForegroundService)

I followed your article describing the sample code to the letter and when I tested it, I could not get any notification at all. When I follow the running services from the developer options, when the application first runs and I send a message with the button, it appears and disappears in the running services instantly. I wonder where the problem is?

[My Code](https://gist.github.com/mthnzbk/8ded2980b62fbb76b9c619c3c29820e5)

**Comment by putridparrot** [comment]
Did you run the code from this repository (https://github.com/putridparrot/blog-projects/tree/master/MauiAndroidForegroundService) to see if that worked, as I just tried that and the service starts and remains until I click the stop service button. I'm currently running against the Android emulator Pixel 3 XL API 29 and all looks to be working. If I get chance later I'll hook up a real device and double check, but looking at your code it all looks okay. Although I do notice you're using the LocalNotifications plugin as well - but I did quickly drop your code into my project and I think it was ok. Anyway I'd suggest you try the repo solution and see if that works, then go from there.

**Comment by putridparrot** [comment]
Closing as all looks fine here

**Comment by gsk143** [comment]
Sorry to bump it but service just breaks with error. Java.Lang.IllegalArgumentException: com.companyname.mauiandroidforegroundservice: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

Using Android API 33 emulator

**Comment by putridparrot** [comment]
That's interesting as I have an app. based upon this post running on an Android API 33 device  - I'm not doing much Android at the moment, but I'll have a look at this when I get a moment.
